### ISSUE TITLE
Find information on group meditations

### ISSUE THREAD

**Issue by DanielMaherDev** [DanielMaherDev/MeditationMinds#1]
As a **member of the meditation community** I can **find information on local meditation group sessions** in order to **attend**

**Comment by DanielMaherDev** [comment]
# Acceptance Criteria

* A dedicated section should be provided for information on group meditation sessions
* The information here should be clear and concise
* It should not need to be regularly updated
* It should contain information on location, time, and details of the session

**Comment by DanielMaherDev** [comment]
# Tasks

- [x]  Implement a section on the homepage dedicated to information on group meditation 
- [ ] Use semantics which display information in order of important
- [ ] Add relevant images into the background of the mediation session
